name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit
  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Rename sksud
        run: |
          mkdir -p sksud
          for dir in ./sksud-*; do
              if [ -d "$dir" ]; then
                 echo "----- Rename $dir -----"
                 sksud_platform_name=$(basename "$dir")
                 find "$dir" -type f -name "sksud" -path "*/release/*" | while read -r sksud_file; do
                   if [ -f "$sksud_file" ]; then
                     mv "$sksud_file" "sksud/$sksud_platform_name"
                   fi
                 done
              fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manager/*.apk
            android*-lkm/*_sxkernelsu.ko
            sksud/sksud-*
            sksuinit/**
